name: Run Music Downloader

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use Ubuntu for compatibility
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches the repository code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use latest Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp mutagen requests bs4 pydub musicbrainzngs

      - name: Run Python Script
        run: python script.py  # Runs the main script

      - name: Commit and Push Changes
        run: |
          # Configure git user to commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Add all changes (new files, modified files)
          git add .

          # Commit with a message
          git commit -m "Automated: Music downloader updates"

          # Push changes to master branch
          git push origin master
        env:
          # Use a GitHub token to authenticate and push changes
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
